server:
  port: 8070


grpc:
  server:
    port: 9020


spring:
  redis:
    host: 192.168.196.129
    port: 6379
    password: 1124
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
